CREATE database hunters;
show databases;
use hunters;
grant all privileges on hunters.* to 'hunters'@'%' identified by 'hunters';
grant all privileges on hunters.* to 'hunters'@'localhost' identified by 'hunters';
flush privileges;
use itailor;
show tables;
select * from accesscontrol;
select * from account_groups;
select * from accounts;
select * from comments;
select * from feedback;
select * from groups;
select * from loginrecords;
select * from messages;
select * from shareitems;
select * from timeline;
